const express = require('express')
const request = require('request')
const cheerio = require('cheerio')
const bodyParser = require('body-parser')
const cors = require('cors')

const app = express()

app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.listen(4000, function() {
  console.log(
    `API listening on port ${this.address().port} in ${app.settings.env} mode`
  )
})

app.post('/league', (req, res) => {
  url = `https://globoesporte.globo.com/futebol/${req.body.league}`
  request(url, (error, response, html) => {
    if (!error) {
      const $ = cheerio.load(html)
      let list = []
      $('.tabela-times tbody tr').each((index, item) => {
        let club = {}
        club.name = $(item)
          .find('.tabela-times-time-nome')
          .text()
        club.acronym = $(item)
          .find('.tabela-times-time-sigla')
          .text()
        list.push(club)
      })
      $('.tabela-pontos tbody tr').each((index, item) => {
        list[index].points = $(item)
          .find('.tabela-pontos-ponto')
          .text()
        list[index].played = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .text()
        list[index].won = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .text()
        list[index].drawn = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .text()
        list[index].lost = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].goalsFor = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].goalsAgainst = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].goalDifference = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].percentage = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
      })
      res.send(list)
    } else {
      res.send("Couldn't fetch the data.")
    }
  })
})
