const functions = require('firebase-functions')
const express = require('express')
const request = require('request')
const cheerio = require('cheerio')
const cors = require('cors')
const leagues = require('./leagues')

const app = express()
const port = 4000

app.use(cors())

app.listen(port, () => {
  console.log(`API listening on port ${port} in ${app.settings.env} mode`)
})

app.get('/', (req, res) => {
  res.send({ message: 'Server running gracefully 🦄', timestamp: Date.now() })
})

app.get('/league/:league', (req, res) => {
  res.set('Cache-Control', 'public, max-age=300, s-maxage=600')
  const league = leagues.find(each => each.path === req.params.league)
  const url = `https://globoesporte.globo.com/futebol/${league.url}`
  request(url, (error, response, html) => {
    if (!error) {
      const $ = cheerio.load(html)
      const list = []
      $('.tabela-times tbody tr').each((index, item) => {
        const club = {}
        club.name = $(item)
          .find('.tabela-times-time-nome')
          .text()
        club.acronym = $(item)
          .find('.tabela-times-time-sigla')
          .text()
        list.push(club)
      })
      $('.tabela-pontos tbody tr').each((index, item) => {
        list[index].points = $(item)
          .find('.tabela-pontos-ponto')
          .text()
        list[index].played = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .text()
        list[index].won = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .text()
        list[index].drawn = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .text()
        list[index].lost = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].goalsFor = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].goalsAgainst = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
        const gd = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
        list[index].goalDifference = parseInt(gd) > 0 ? `+${gd}` : gd
        list[index].percentage = $(item)
          .find('.tabela-pontos-ponto')
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .next()
          .text()
      })
      res.send(list)
    } else {
      res.send({ message: "Couldn't fetch the data.", timestamp: Date.now() })
    }
  })
})

exports.app = functions.https.onRequest(app)
